introduction:
  title: Introduction
quickStart:
  title: Quick Start
views:
  title: Views and Dependency Injection
scopes:
  title: Vaadin Scopes
nettyRuntime:
  title: Running on Netty
servletRuntime:
  title: Running on a Servlet Container
devMode:
  title: Development Mode
testing:
  title: Testing
repository: Repository
releaseHistory: Release History
