plugins {
    id 'io.micronaut.build.internal.kotlin-ksp'
    id 'io.micronaut.build.internal.vaadin-tests'
}

dependencies {
    kspTest(mn.micronaut.inject.kotlin)
    testImplementation(projects.micronautVaadinCore)
    testImplementation(mnTest.micronaut.test.junit5)
    testRuntimeOnly(mnLogging.logback.classic)
}
